const { Product } = require("../models");

const productData = [
  {
    product_name: "Plain T-Shirt",
    category: "fashion",
    price: 14.99,
    condition: 5,
    city: "New York",
    contact_info: "6456899999",
    description: "A plain t-shirt for everyday wear.",
    stock: 1,
    image: "https://example.com/images/plain-tshirt.jpg",
  },
  {
    product_name: "Running Sneakers",
    category: "fashion",
    price: 90.0,
    condition: 8,
    city: "Los Angeles",
    contact_info: "6543219876",
    description: "High-performance running sneakers.",
    stock: 2,
    image: "https://example.com/images/running-sneakers.jpg",
  },
  {
    product_name: "Branded Baseball Hat",
    category: "fashion",
    price: 22.99,
    condition: 6,
    city: "Chicago",
    contact_info: "9876543210",
    description: "A stylish baseball hat with a brand logo.",
    stock: 3,
    image: "https://example.com/images/baseball-hat.jpg",
  },
  {
    product_name: "Wooden Coffee Table",
    category: "furniture",
    price: 199.99,
    condition: 9,
    city: "New York",
    contact_info: "6456899999",
    description: "A beautiful wooden coffee table for your living room.",
    stock: 1,
    image: "https://example.com/images/wooden-coffee-table.jpg",
  },
  {
    product_name: "Leather Sofa",
    category: "furniture",
    price: 799.0,
    condition: 8,
    city: "Los Angeles",
    contact_info: "6543219876",
    description: "A luxurious leather sofa for ultimate comfort.",
    stock: 1,
    image: "https://example.com/images/leather-sofa.jpg",
  },
  {
    product_name: "Modern Dining Set",
    category: "furniture",
    price: 599.99,
    condition: 7,
    city: "Chicago",
    contact_info: "9876543210",
    description: "A sleek and stylish dining set for your home.",
    stock: 1,
    image: "https://example.com/images/modern-dining-set.jpg",
  },
  {
    product_name: 'Smartphone',
    category: "electronics",
    price: 799.99,
    condition: 10,
    city: 'San Francisco',
    contact_info: '1234567890',
    description: 'The latest smartphone with advanced features.',
    stock: 1,
    image: 'https://example.com/images/smartphone.jpg',
  },
  {
    product_name: 'Laptop',
    category: "electronics",
    price: 1299.0,
    condition: 9,
    city: 'Seattle',
    contact_info: '0987654321',
    description: 'A powerful laptop for all your computing needs.',
    stock: 1,
    image: 'https://example.com/images/laptop.jpg',
  },
  {
    product_name: 'Wireless Earphones',
    category: "electronics",
    price: 99.99,
    condition: 8,
    city: 'Miami',
    contact_info: '4567891230',
    description: 'High-quality wireless earphones for immersive audio.',
    stock: 1,
    image: 'https://example.com/images/wireless-earphones.jpg',
  },

];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
